version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8800:8800"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb+srv://prajwalkum03airs:Be6uXCtwc4YZfpc0@cluster0.cbi70.mongodb.net/task?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=JHNFVDGSNKUGJKLHVBNR
      - PORT=8800
      - NODE_ENV=development
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

# Define networks
networks:
  app-network:
    driver: bridge

# Define volumes
volumes:
  mongodb_data:
  redis_data: 